resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    managers
    workers

    [managers:children]
    active
    standby

    [active]
    node01.netology.yc ansible_host=${yandex_compute_instance.node01.network_interface.0.nat_ip_address} ansible_ssh_private_key_file=~/.ssh/ya-cloud

    [standby]
    node02.netology.yc ansible_host=${yandex_compute_instance.node02.network_interface.0.nat_ip_address} ansible_ssh_private_key_file=~/.ssh/ya-cloud
    node03.netology.yc ansible_host=${yandex_compute_instance.node03.network_interface.0.nat_ip_address} ansible_ssh_private_key_file=~/.ssh/ya-cloud

    [workers]
    node04.netology.yc ansible_host=${yandex_compute_instance.node04.network_interface.0.nat_ip_address} ansible_ssh_private_key_file=~/.ssh/ya-cloud
    node05.netology.yc ansible_host=${yandex_compute_instance.node05.network_interface.0.nat_ip_address} ansible_ssh_private_key_file=~/.ssh/ya-cloud
    node06.netology.yc ansible_host=${yandex_compute_instance.node06.network_interface.0.nat_ip_address} ansible_ssh_private_key_file=~/.ssh/ya-cloud
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.node01,
    yandex_compute_instance.node02,
    yandex_compute_instance.node03,
    yandex_compute_instance.node04,
    yandex_compute_instance.node05,
    yandex_compute_instance.node06
  ]
}
